### ISSUE TITLE
Issue with @typescript-eslint eslint.config.js is now the standard format

### ISSUE THREAD

**Issue by v3nt** [serifcolakel/mfe-tutorial#2]
Cant run this to build a new micro fe in the main app - 
```pnpm exec nx generate @nx/react:host --name=container --devServerPort=3000 --directory=apps/container --remotes=info --projectNameAndRootFormat=as-provided --no-interactive --dry-run --verbose```

Errors
```
NX   Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it. See errors below.

Failed to process project graph. Run "nx reset" to fix this. Please report the issue if you keep seeing it.
      An error occurred while processing files for the @nx/eslint/plugin plugin.
    - apps/mfe-nx-react-tw/eslint.config.js: Key "rules": Key "@typescript-eslint/no-array-constructor": Could not find plugin "@typescript-eslint".
      TypeError: Key "rules": Key "@typescript-eslint/no-array-constructor": Could not find plugin "@typescript-eslint".
          at throwRuleNotFoundError (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/eslint@9.11.1_jiti@1.21.6/node_modules/eslint/lib/config/rule-validator.js:66:11)
          at RuleValidator.validate (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/eslint@9.11.1_jiti@1.21.6/node_modules/eslint/lib/config/rule-validator.js:147:17)
          at new Config (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/eslint@9.11.1_jiti@1.21.6/node_modules/eslint/lib/config/config.js:240:27)
          at [finalizeConfig] (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/eslint@9.11.1_jiti@1.21.6/node_modules/eslint/lib/config/flat-config-array.js:216:16)
          at FlatConfigArray.getConfigWithStatus (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/@eslint+config-array@0.18.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1102:55)
          at FlatConfigArray.getConfig (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/@eslint+config-array@0.18.0/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
          at ESLint.calculateConfigForFile (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/eslint@9.11.1_jiti@1.21.6/node_modules/eslint/lib/eslint/eslint.js:1276:24)
          at async ESLint.isPathIgnored (/Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/eslint@9.11.1_jiti@1.21.6/node_modules/eslint/lib/eslint/eslint.js:1298:24)
          at async /Users/username/Sites/learning/react/mfe-nx-react-tw/node_modules/.pnpm/@nx+eslint@19.8.2_@babel+traverse@7.25.6_@swc-node+register@1.9.2_@swc+core@1.5.29_@swc+helpe_oxbwdvyl4yal7opupli33bx25y/node_modules/@nx/eslint/src/plugins/plugin.js:123:19
          at async Promise.all (index 0)```

**Comment by serifcolakel** [comment]
@v3nt hi, thank you your feedback. First of all can u switch data-layer branch. After switching branch can u try `pnpm exec nx generate @nx/react:host --name=test --devServerPort=3000 --directory=apps/test --remotes=test-info --projectNameAndRootFormat=as-provided --no-interactive --verbose` without `--dry-run` flag. 

My Local package configuration like this

`
serifcolakel@Serif-MacBook-Pro mfe-tutorial % node -v
v22.9.0
serifcolakel@Serif-MacBook-Pro mfe-tutorial % pnpm nx --version
Nx Version:
- Local: v17.0.1
- Global: Not found

`

You can Nx Workspace extension on VS Code.

![Screenshot 2024-10-01 at 13 29 39](https://github.com/user-attachments/assets/67f09409-7210-4aee-b6e3-25bda1466ed0)
